import { useSettings } from "@/lib/i18n/SettingsContext";

const en = {
  kicker: "Plans",
  title: "Choose how you study",
  lead: "Start free. Basic removes the daily limit for lectures; Pro adds the SAT, IELTS and TOEFL prep area.",
  monthly: "Monthly",
  yearly: "Yearly",
  save: (percent: number) => `Save ${percent}%`,
  perMonth: "/ month",
  perYear: "/ year",
  free: "Free",
  freePrice: "$0",
  freeNote: "For trying Lumina",
  basic: "Basic",
  basicNote: "For regular lecture study",
  pro: "Pro",
  proNote: "Everything, including exam prep",
  upgradeNote: "Your Basic plan is cancelled automatically when Pro starts.",
  switchLater: "To move to Basic, cancel Pro and subscribe to Basic after it ends.",
  current: "Current plan",
  features: {
    lectures: (n: number) => `${n} lecture generations a day`,
    length: (n: number) => `Lectures up to ${n.toLocaleString("en-US")} characters`,
    materials: "Summary, key points, quiz and flashcards",
    sources: "Every item linked to the source",
    prep: "SAT, IELTS and TOEFL reading practice",
    prepSets: (n: number) => `${n} practice sets a day, up to 15 questions`,
    noPrep: "Exam prep area",
  },
  signIn: "Sign in to subscribe",
  notConfigured: "Payments are not set up on this server yet.",
  loading: "Loading plans…",
  activating: "Confirming your subscription…",
  welcome: "Your subscription is confirmed. Your new limits are active.",
  paypalError: "We could not confirm the payment status. Check your PayPal activity before trying again. If you have already paid, restore your subscription below instead of paying again.",
  pendingConfirmation: "PayPal approval was received, but membership still needs confirmation. Do not pay again. Retry syncing this subscription after the server issue is resolved.",
  retryConfirmation: "Sync existing subscription (no new payment)",
  restoreTitle: "Already paid? Restore your subscription",
  restoreHelp: "Enter the PayPal subscription / billing agreement ID starting with I-. This checks an existing subscription; it does not create a new one.",
  subscriptionId: "PayPal subscription ID",
  invalidSubscriptionId: "Enter a subscription ID starting with I-, not a transaction ID or plan ID.",
  manage: "Your subscription",
  renews: (date: string) => `Renews on ${date}`,
  endsOn: (date: string) => `Pro until ${date}, then Free`,
  interval: { monthly: "Monthly", yearly: "Yearly" } as Record<string, string>,
  cancel: "Cancel subscription",
  cancelConfirm: "Stop renewing Pro? You keep Pro until the end of the period you paid for.",
  cancelling: "Cancelling…",
  cancelled: "Renewal stopped.",
  suspended: "PayPal could not collect the last payment. Update your payment method in PayPal to keep Pro.",
  secure: "Payments are processed by PayPal. Lumina never sees your card details. Cancel any time.",
  usageTitle: "Today",
  usageLecture: (used: number, limit: number) => `${used} of ${limit} generations used`,
  resets: "Resets at midnight UTC",
  upgrade: "Upgrade",
  upgradeToPro: "Upgrade to Pro",
  upgradePlan: "Upgrade your plan",
  planName: { free: "Free", basic: "Basic", pro: "Pro" } as Record<string, string>,
  proBadge: "Pro",
  remaining: (left: number, limit: number) => `${left} of ${limit} free generations left today`,
  lockedTitle: "Exam prep is part of Lumina Pro",
  lockedLead: "Practise with SAT, IELTS and TOEFL style questions written from any passage, with every answer checked against the text. Basic does not include exam prep.",
  seePlans: "See plans",
};
type Copy = typeof en;

const zh: Copy = {
  kicker: "方案",
  title: "选择适合你的方案",
  lead: "先免费使用。基础版解除讲稿每日限制；Pro 再加上 SAT、雅思、托福备考专区。",
  monthly: "按月",
  yearly: "按年",
  save: (percent) => `省 ${percent}%`,
  perMonth: "/ 月",
  perYear: "/ 年",
  free: "免费版",
  freePrice: "$0",
  freeNote: "适合先试用",
  basic: "基础版",
  basicNote: "适合日常讲稿学习",
  pro: "Pro 会员",
  proNote: "全部功能，包括备考专区",
  upgradeNote: "开通 Pro 后，基础版订阅会自动取消。",
  switchLater: "想换成基础版：先取消 Pro，到期后再订阅基础版。",
  current: "当前方案",
  features: {
    lectures: (n) => `每天 ${n} 次讲稿生成`,
    length: (n) => `讲稿最长 ${n.toLocaleString("en-US")} 字符`,
    materials: "摘要、要点、测验和闪卡",
    sources: "每一条都能追溯到原文",
    prep: "SAT、雅思、托福阅读练习",
    prepSets: (n) => `每天 ${n} 套练习，每套最多 15 题`,
    noPrep: "备考专区",
  },
  signIn: "登录后订阅",
  notConfigured: "服务器还没有配置支付。",
  loading: "正在加载方案…",
  activating: "正在确认订阅…",
  welcome: "订阅确认成功，新的额度已生效。",
  paypalError: "暂时无法确认付款状态。请先查看 PayPal 交易记录；如果已经付款，请在下方恢复订阅，不要再次支付。",
  pendingConfirmation: "已收到 PayPal 的订阅批准，但会员状态尚未确认。请勿重复付款；服务器问题解决后，重新同步这笔订阅。",
  retryConfirmation: "同步已有订阅（不重新付款）",
  restoreTitle: "已经付款？恢复订阅",
  restoreHelp: "填写 PayPal 中以 I- 开头的订阅／自动付款协议编号。这里只核验已有订阅，不会创建新的订阅。",
  subscriptionId: "PayPal 订阅编号",
  invalidSubscriptionId: "请输入以 I- 开头的订阅编号，不是交易编号或 P- 开头的套餐编号。",
  manage: "我的订阅",
  renews: (date) => `将于 ${date} 自动续费`,
  endsOn: (date) => `Pro 有效期至 ${date}，之后转为免费版`,
  interval: { monthly: "按月", yearly: "按年" },
  cancel: "取消订阅",
  cancelConfirm: "确定停止续费吗？已付费的周期结束前仍可使用 Pro。",
  cancelling: "正在取消…",
  cancelled: "已停止续费。",
  suspended: "PayPal 未能扣取上一期费用。请在 PayPal 更新付款方式以继续使用 Pro。",
  secure: "付款由 PayPal 处理，Lumina 不会接触你的卡号。可随时取消。",
  usageTitle: "今天",
  usageLecture: (used, limit) => `已用 ${used} / ${limit} 次生成`,
  resets: "UTC 零点重置",
  upgrade: "升级",
  upgradeToPro: "升级到 Pro",
  upgradePlan: "升级方案",
  planName: { free: "免费版", basic: "基础版", pro: "Pro 会员" },
  proBadge: "Pro",
  remaining: (left, limit) => `今天还剩 ${left} / ${limit} 次免费生成`,
  lockedTitle: "备考专区是 Pro 会员功能",
  lockedLead: "用任意文章生成 SAT、雅思、托福题型的练习，每个答案都对照原文核验。基础版不包含备考专区。",
  seePlans: "查看方案",
};

export function useBillingCopy() {
  const { language } = useSettings();
  const isZh = language === "zh";
  return { c: isZh ? zh : en, locale: isZh ? "zh-CN" : "en-US" };
}
