import { useSettings } from "@/lib/i18n/SettingsContext";

const en = {
  eyebrow: "Exam prep",
  homeTitle: "Reading practice for SAT, IELTS and TOEFL",
  homeLead: "Paste an English passage and practise with questions in the format of your exam. Every answer can be traced back to the text.",
  disclaimer: "Lumina is not affiliated with College Board, IDP, the British Council, Cambridge or ETS. Questions are original practice material and scores are estimates.",
  start: "Start practising",
  target: "Target",
  noTarget: "No target set",
  daysLeft: (n: number) => n > 0 ? `${n} days to go` : n === 0 ? "Exam day" : "Exam date passed",
  noDate: "Set your exam date",
  lastScore: "Last",
  noPractice: "No practice yet",
  back: "All exams",
  sections: "Sections",
  soon: "Coming soon",
  moreSoon: "Other sections are coming soon.",
  profile: "Your plan",
  examDate: "Exam date",
  save: "Save",
  saved: "Saved",
  passage: "Passage",
  passagePlaceholder: "Paste the passage here…",
  characters: (n: number, max: number) => `${n.toLocaleString("en-US")} / ${max.toLocaleString("en-US")} characters`,
  questionTypes: "Question types",
  generate: "Create questions",
  generating: "Writing questions",
  generatingHint: "Each answer is checked against the passage. This usually takes under a minute.",
  cancel: "Cancel",
  tooShort: (n: number) => `Add at least ${n} characters of passage text.`,
  pickType: "Choose at least one question type.",
  networkError: "Could not reach the server. Try again.",
  questionOf: (i: number, n: number) => `Question ${i} of ${n}`,
  answerPlaceholder: "Type your answer",
  submit: "Check answers",
  answered: (a: number, n: number) => `${a} of ${n} answered`,
  results: "Results",
  score: (c: number, n: number) => `${c} / ${n} correct`,
  band: (b: number) => `Estimated band ≈ ${b}`,
  percent: (p: number) => `${p}% accuracy`,
  estimateNote: "Rough estimate scaled from this set; real tests vary.",
  correct: "Correct",
  incorrect: "Incorrect",
  yourAnswer: "Your answer",
  correctAnswer: "Answer",
  showInPassage: "Show in passage",
  retry: "Try again",
  newSet: "New passage",
  history: "Recent practice",
  explanationLanguage: "Explanations in Chinese",
};
type Copy = typeof en;

const zh: Copy = {
  eyebrow: "备考",
  homeTitle: "SAT、雅思与托福阅读练习",
  homeLead: "粘贴一篇英文文章，按考试题型生成练习。每个答案都能在原文中找到依据。",
  disclaimer: "Lumina 与 College Board、IDP、British Council、Cambridge、ETS 均无关联。题目为原创练习材料，分数仅为估算。",
  start: "开始练习",
  target: "目标",
  noTarget: "未设定目标",
  daysLeft: (n) => n > 0 ? `距离考试 ${n} 天` : n === 0 ? "今天考试" : "考试日期已过",
  noDate: "设置考试日期",
  lastScore: "最近",
  noPractice: "还没有练习",
  back: "全部考试",
  sections: "科目",
  soon: "即将上线",
  moreSoon: "其他科目即将上线。",
  profile: "我的计划",
  examDate: "考试日期",
  save: "保存",
  saved: "已保存",
  passage: "文章",
  passagePlaceholder: "在这里粘贴文章…",
  characters: (n, max) => `${n.toLocaleString("en-US")} / ${max.toLocaleString("en-US")} 字符`,
  questionTypes: "题型",
  generate: "生成题目",
  generating: "正在出题",
  generatingHint: "每个答案都会对照原文核验，通常不到一分钟。",
  cancel: "取消",
  tooShort: (n) => `文章至少需要 ${n} 个字符。`,
  pickType: "请至少选择一种题型。",
  networkError: "无法连接服务器，请重试。",
  questionOf: (i, n) => `第 ${i} / ${n} 题`,
  answerPlaceholder: "输入答案",
  submit: "提交答案",
  answered: (a, n) => `已作答 ${a} / ${n}`,
  results: "成绩",
  score: (c, n) => `答对 ${c} / ${n}`,
  band: (b) => `估算分数 ≈ ${b}`,
  percent: (p) => `正确率 ${p}%`,
  estimateNote: "按本套题比例粗略换算，仅供参考。",
  correct: "正确",
  incorrect: "错误",
  yourAnswer: "你的答案",
  correctAnswer: "答案",
  showInPassage: "定位原文",
  retry: "重做",
  newSet: "换一篇文章",
  history: "最近练习",
  explanationLanguage: "中文解析",
};

export function usePrepCopy() {
  const { language } = useSettings();
  const isZh = language === "zh";
  return { c: isZh ? zh : en, lang: isZh ? "zh" as const : "en" as const };
}
